events {
    worker_connections 1024;
}

pid /tmp/sitio1.pid;

http {
    server {
        listen 81;

        location / {
            root /mnt/c/Users/mrubi/OneDrive/Escaneos/Desktop/17289/17289/nginx/3sitios/sitio1;
            index index.html;
        }
    }
}